"""Column registry: the single source of truth for what the table can show.

Each :class:`ColumnSpec` carries the DataFrame key, a label, a group, a format
and a tooltip (the metric definition). ``sign`` states whether larger values
are favourable (``+1``), unfavourable (``-1``) or neutral (``0``); it drives
conditional colouring. ``default`` marks the columns of the Overview preset.
"""

from __future__ import annotations

from dataclasses import dataclass

GROUPS = [
    "Identification",
    "Performance",
    "Technicals",
    "Volume",
    "Volatility",
    "Options: Expectations",
    "Options: Downside risk",
    "Options: Flow",
    "Fundamentals",
    "Scores",
    "Quality",
]


@dataclass(frozen=True)
class ColumnSpec:
    key: str
    label: str
    group: str
    fmt: str = "num"  # pct | pct2 | num | num2 | int | money | text | score | vol
    tooltip: str = ""
    sign: int = 0
    default: bool = False
    width: int | None = None


C = ColumnSpec
COLUMNS: list[ColumnSpec] = [
    # identification
    C("ticker", "Ticker", "Identification", "text", "Stock symbol", default=True, width=95),
    C("name", "Name", "Identification", "text", "Company name", default=True, width=170),
    C(
        "sector",
        "Sector",
        "Identification",
        "text",
        "SIC industry description",
        default=True,
        width=170,
    ),
    C("price", "Price", "Identification", "num2", "Last daily close (adjusted)", default=True),
    C("change_1d", "Chg 1d", "Identification", "pct", "One-day close-to-close return", 1, True),
    C("market_cap", "Mkt cap", "Identification", "money", "Market capitalisation (USD)", 0, True),
    C(
        "dollar_volume_20",
        "$ vol 20d",
        "Identification",
        "money",
        "Average daily dollar volume, 20 days",
        0,
        True,
    ),
    # performance
    C("ret_1w", "Ret 1w", "Performance", "pct", "Return over 5 trading days", 1),
    C("ret_1m", "Ret 1m", "Performance", "pct", "Return over 21 trading days", 1, True),
    C("ret_3m", "Ret 3m", "Performance", "pct", "Return over 63 trading days", 1, True),
    C("ret_6m", "Ret 6m", "Performance", "pct", "Return over 126 trading days", 1),
    C("ret_1y", "Ret 1y", "Performance", "pct", "Return over 252 trading days", 1, True),
    C("ret_ytd", "Ret YTD", "Performance", "pct", "Return since last close of prior year", 1),
    C(
        "max_dd_1y",
        "Max DD 1y",
        "Performance",
        "pct",
        "Maximum peak-to-trough drawdown over 1 year",
        1,
    ),
    C(
        "ret_vol_1y",
        "Ret/Vol 1y",
        "Performance",
        "num2",
        "Log return 1y divided by realised vol 1y (Sharpe-like, zero rate)",
        1,
    ),
    C(
        "beta_1y",
        "Beta 1y",
        "Performance",
        "num2",
        "Beta of daily log returns vs the benchmark (SPY), 1 year",
        0,
    ),
    C(
        "dist_52w_high",
        "vs 52w high",
        "Performance",
        "pct",
        "Distance of price from the 52-week high",
        1,
    ),
    C(
        "dist_52w_low",
        "vs 52w low",
        "Performance",
        "pct",
        "Distance of price from the 52-week low",
        0,
    ),
    # technicals
    C("mom_20", "Mom 20", "Technicals", "pct", "Rate of change over 20 days", 1),
    C("mom_60", "Mom 60", "Technicals", "pct", "Rate of change over 60 days", 1, True),
    C("mom_120", "Mom 120", "Technicals", "pct", "Rate of change over 120 days", 1),
    C(
        "trend_score",
        "Trend",
        "Technicals",
        "num2",
        "Trend score in [-1, 1]: price vs SMA50/200, SMA50 slope, SMA50>SMA200",
        1,
        True,
    ),
    C(
        "sma50_dist",
        "vs SMA50",
        "Technicals",
        "pct",
        "Price relative to 50-day simple moving average",
        1,
    ),
    C(
        "sma200_dist",
        "vs SMA200",
        "Technicals",
        "pct",
        "Price relative to 200-day simple moving average",
        1,
    ),
    C("sma50_slope", "SMA50 slope", "Technicals", "pct", "Change of SMA50 over 20 days", 1),
    C("rsi_14", "RSI 14", "Technicals", "num", "Wilder relative strength index, 14 days", 0, True),
    C(
        "macd_hist",
        "MACD hist",
        "Technicals",
        "pct2",
        "MACD histogram (12/26/9) as a fraction of price",
        1,
    ),
    C("atr_pct", "ATR %", "Technicals", "pct", "Average true range (14) as a fraction of price", 0),
    C(
        "bb_pct_b",
        "Bollinger %B",
        "Technicals",
        "num2",
        "Position within the 20-day, 2-sigma Bollinger band (0 = lower, 1 = upper)",
        0,
    ),
    C("adx_14", "ADX 14", "Technicals", "num", "Average directional index (trend strength)", 0),
    # volume
    C("volume", "Volume", "Volume", "int", "Last day share volume", 0),
    C("avg_volume_20", "Avg vol 20", "Volume", "int", "Average share volume, 20 days", 0),
    C(
        "volume_trend",
        "Vol trend",
        "Volume",
        "pct",
        "20-day average volume relative to 60-day average, minus 1",
        0,
        True,
    ),
    C("rel_volume", "Rel vol", "Volume", "num2", "Last day volume divided by 20-day average", 0),
    C(
        "obv_slope_20",
        "OBV slope",
        "Volume",
        "num2",
        "Slope of on-balance volume over 20 days, normalised by average volume",
        1,
    ),
    # volatility
    C(
        "rv_20",
        "RV 20",
        "Volatility",
        "vol",
        "Realised volatility of log returns, 20 days, annualised",
        0,
        True,
    ),
    C("rv_60", "RV 60", "Volatility", "vol", "Realised volatility, 60 days, annualised", 0),
    C("rv_252", "RV 1y", "Volatility", "vol", "Realised volatility, 252 days, annualised", 0),
    C(
        "iv_30",
        "IV 30",
        "Volatility",
        "vol",
        "Constant-maturity 30-day at-the-forward implied volatility",
        0,
        True,
    ),
    C("iv_60", "IV 60", "Volatility", "vol", "Constant-maturity 60-day implied volatility", 0),
    C("iv_90", "IV 90", "Volatility", "vol", "Constant-maturity 90-day implied volatility", 0),
    C(
        "iv_rank",
        "IV rank",
        "Volatility",
        "pct",
        "(IV30 - 1y min) / (1y max - 1y min) from stored history",
        0,
    ),
    C(
        "iv_percentile",
        "IV pctile",
        "Volatility",
        "pct",
        "Share of the last year's IV30 observations below today's",
        0,
    ),
    C(
        "iv_rv_ratio",
        "IV/RV",
        "Volatility",
        "num2",
        "IV30 divided by realised vol 20d (volatility risk premium ratio)",
        0,
        True,
    ),
    C("vol_risk_premium", "IV-RV", "Volatility", "vol", "IV30 minus realised vol 20d", 0),
    C("term_slope", "Term slope", "Volatility", "vol", "IV90 minus IV30 (positive = contango)", 0),
    C(
        "skew_25d",
        "Skew 25d",
        "Volatility",
        "vol",
        "IV(25-delta put) minus IV(25-delta call) at ~30 days",
        -1,
    ),
    C("skew_25d_rel", "Skew/ATM", "Volatility", "pct", "25-delta skew as a fraction of ATM IV", -1),
    C(
        "put_tail_10d",
        "Put tail",
        "Volatility",
        "vol",
        "IV(10-delta put) minus ATM IV at ~30 days",
        -1,
    ),
    # options: expectations (risk-neutral)
    C(
        "expected_move",
        "Exp move 30d",
        "Options: Expectations",
        "pct",
        "Std. dev. of the 30-day risk-neutral return distribution",
        0,
        True,
    ),
    C(
        "atm_straddle_move_30",
        "Straddle move",
        "Options: Expectations",
        "pct",
        "ATM straddle price / forward at the expiry nearest 30 days",
        0,
    ),
    C(
        "rn_mean_ret",
        "RN mean",
        "Options: Expectations",
        "pct2",
        "Risk-neutral expected 30-day return (≈ carry, r - q)",
        0,
    ),
    C(
        "rn_median_ret",
        "RN median",
        "Options: Expectations",
        "pct2",
        "Median of the risk-neutral 30-day return distribution",
        1,
    ),
    C(
        "p_gain_5",
        "P(+5%)",
        "Options: Expectations",
        "pct",
        "Risk-neutral probability of a gain of at least 5% in 30 days",
        1,
    ),
    C(
        "p_gain_10",
        "P(+10%)",
        "Options: Expectations",
        "pct",
        "Risk-neutral probability of a gain of at least 10% in 30 days",
        1,
        True,
    ),
    C(
        "rn_skew",
        "RN skew",
        "Options: Expectations",
        "num2",
        "Skewness of the risk-neutral 30-day return",
        1,
    ),
    C(
        "rn_kurtosis",
        "RN kurt",
        "Options: Expectations",
        "num2",
        "Excess kurtosis of the risk-neutral 30-day return",
        -1,
    ),
    C(
        "implied_carry",
        "Impl. carry",
        "Options: Expectations",
        "pct2",
        "ln(F/S)/T - r from put-call parity (≈ -dividend yield - borrow)",
        0,
    ),
    C(
        "max_pain",
        "Max pain",
        "Options: Expectations",
        "num2",
        "Strike minimising option holders' payoff at the nearest expiry ≥ 14 days",
        0,
    ),
    C(
        "max_pain_dist",
        "Max pain %",
        "Options: Expectations",
        "pct",
        "Max pain strike relative to spot",
        0,
    ),
    # options: downside risk
    C(
        "p_loss_5",
        "P(-5%)",
        "Options: Downside risk",
        "pct",
        "Risk-neutral probability of a loss of at least 5% in 30 days",
        -1,
    ),
    C(
        "p_loss_10",
        "P(-10%)",
        "Options: Downside risk",
        "pct",
        "Risk-neutral probability of a loss of at least 10% in 30 days",
        -1,
        True,
    ),
    C(
        "p_loss_20",
        "P(-20%)",
        "Options: Downside risk",
        "pct",
        "Risk-neutral probability of a loss of at least 20% in 30 days",
        -1,
    ),
    C(
        "var_5",
        "VaR 5%",
        "Options: Downside risk",
        "pct",
        "5th percentile of the risk-neutral 30-day return",
        1,
        True,
    ),
    C(
        "es_5",
        "ES 5%",
        "Options: Downside risk",
        "pct",
        "Expected shortfall: mean return below the 5th percentile (30 days)",
        1,
        True,
    ),
    C(
        "rn_semi_dev",
        "Semi-dev",
        "Options: Downside risk",
        "pct",
        "Downside deviation of the risk-neutral 30-day return",
        -1,
    ),
    C(
        "tail_asymmetry",
        "Tail asym.",
        "Options: Downside risk",
        "pct",
        "P(-10%) minus P(+10%): positive = downside-heavy",
        -1,
    ),
    C(
        "expected_move_vs_atr",
        "Move/ATR",
        "Options: Downside risk",
        "num2",
        "Expected move relative to ATR scaled to 30 days",
        0,
    ),
    # flow
    C(
        "pc_oi_ratio",
        "P/C OI",
        "Options: Flow",
        "num2",
        "Put open interest / call open interest (cleaned chain)",
        -1,
    ),
    C("pc_volume_ratio", "P/C vol", "Options: Flow", "num2", "Put volume / call volume", -1),
    C("option_volume", "Opt volume", "Options: Flow", "int", "Total option contracts traded", 0),
    C("open_interest", "Open int.", "Options: Flow", "int", "Total open interest", 0, True),
    C("liquidity_score", "Opt liq.", "Options: Flow", "num2", "log10(1 + total open interest)", 1),
    # fundamentals
    C("pe", "P/E", "Fundamentals", "num", "Price / trailing-twelve-month earnings", -1, True),
    C("pb", "P/B", "Fundamentals", "num", "Price / book value", -1),
    C("ps", "P/S", "Fundamentals", "num", "Price / TTM sales", -1),
    C("p_fcf", "P/FCF", "Fundamentals", "num", "Price / TTM free cash flow", -1),
    C("ev_ebitda", "EV/EBITDA", "Fundamentals", "num", "Enterprise value / TTM EBITDA", -1, True),
    C("ev_sales", "EV/Sales", "Fundamentals", "num", "Enterprise value / TTM sales", -1),
    C("roe", "ROE", "Fundamentals", "pct", "Return on equity, TTM", 1),
    C("roa", "ROA", "Fundamentals", "pct", "Return on assets, TTM", 1),
    C("debt_to_equity", "D/E", "Fundamentals", "num2", "Total debt / equity", -1),
    C(
        "current_ratio",
        "Current",
        "Fundamentals",
        "num2",
        "Current assets / current liabilities",
        1,
    ),
    C("dividend_yield", "Div yield", "Fundamentals", "pct", "Trailing dividend yield", 1),
    C("fcf_yield", "FCF yield", "Fundamentals", "pct", "TTM free cash flow / market cap", 1),
    C("earnings_yield", "Earn. yield", "Fundamentals", "pct", "1 / P/E", 1),
    C("revenue_growth", "Rev growth", "Fundamentals", "pct", "TTM revenue vs prior TTM", 1, True),
    C("gross_margin", "Gross margin", "Fundamentals", "pct", "TTM gross profit / revenue", 1),
    C("net_margin", "Net margin", "Fundamentals", "pct", "TTM net income / revenue", 1),
    # scores
    C(
        "momentum_score",
        "Momentum",
        "Scores",
        "score",
        "Percentile blend of momentum, trend, RSI, volume trend",
        1,
        True,
    ),
    C(
        "quality_score",
        "Quality",
        "Scores",
        "score",
        "Percentile blend of ROE, margins, growth, leverage, FCF yield",
        1,
    ),
    C(
        "value_score",
        "Value",
        "Scores",
        "score",
        "Percentile blend of P/E, EV/EBITDA, P/S, FCF yield",
        1,
    ),
    C(
        "risk_score",
        "Risk",
        "Scores",
        "score",
        "Percentile blend of implied downside, ES, IV, RV, drawdown, skew (higher = riskier)",
        -1,
        True,
    ),
    C(
        "screener_score",
        "Screener",
        "Scores",
        "score",
        "0.7 × mean(momentum, quality, value) + 0.3 × (100 - risk)",
        1,
        True,
    ),
    # quality / diagnostics
    C("n_contracts", "# contracts", "Quality", "int", "Usable option contracts after cleaning", 0),
    C("n_expiries", "# expiries", "Quality", "int", "Expiries with a fitted smile", 0),
    C(
        "fit_rmse",
        "Fit RMSE",
        "Quality",
        "vol",
        "Weighted RMSE of the smile fit at ~30 days (vol points)",
        -1,
    ),
    C(
        "iv_source_vendor_share",
        "Vendor IV %",
        "Quality",
        "pct",
        "Share of contracts using the vendor IV (rest solved with QuantLib)",
        0,
    ),
    C(
        "rn_clipped_mass",
        "Clipped mass",
        "Quality",
        "pct2",
        "Negative density mass removed from the risk-neutral density",
        -1,
    ),
    C(
        "ql_surface_diff",
        "QL check",
        "Quality",
        "vol",
        "Abs. difference between the QuantLib BlackVarianceSurface and the smile surface at the 30d forward",
        -1,
    ),
    C(
        "forward_source",
        "Fwd source",
        "Quality",
        "text",
        "Implied forward from put-call parity or carry fallback",
        0,
    ),
    C("div_yield_used", "q used", "Quality", "pct2", "Dividend yield used for option pricing", 0),
    C("n_warnings", "# warn", "Quality", "int", "Number of data warnings", -1),
    C("warnings", "Warnings", "Quality", "text", "Data warnings", 0, width=260),
]

BY_KEY = {c.key: c for c in COLUMNS}


def columns_in_group(group: str) -> list[ColumnSpec]:
    return [c for c in COLUMNS if c.group == group]
